spring:
  application:
    name: RobotDemo
  datasource:
    url: jdbc:mysql://localhost:3306/chatbot_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: chatbot_user
    password: 123456  # 确保与MySQL root密码一致
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # 修正过时方言
server:
  port: 8080
